'use strict';
const {ACTIONS:ALLOWED_ACTIONS,cleanSignal,docId}=require('./signal-store');
const MAX_SIGNALS=100;
const EXTERNAL_ACTIONS=new Set(['reply','schedule']);
const cleanProposal=value=>{const row=value&&typeof value==='object'?value:{};return{title:String(row.title||'').slice(0,300),summary:String(row.summary||'').slice(0,1000),dueAt:row.dueAt||null,executionClass:String(row.executionClass||'internal_controlled').slice(0,40),payload:{sourceSignalId:String(row.payload?.sourceSignalId||'').slice(0,300),title:String(row.payload?.title||'').slice(0,300),notes:String(row.payload?.notes||'').slice(0,2000),dueAt:row.payload?.dueAt||null,draftOnly:Boolean(row.payload?.draftOnly),calendarWrite:false,publish:false}};};
function createHandlers({onCall,HttpsError,admin,db}){
 const auth=req=>{if(!req.auth)throw new HttpsError('unauthenticated','Authentication required');return req.auth.uid;};
 const audit=(uid,type,data)=>db.collection(`users/${uid}/auditEvents`).add({type,...data,userId:uid,createdAt:admin.firestore.FieldValue.serverTimestamp(),engineVersion:'1.2.0'});
 return {
  syncIntelligenceSignals:onCall(async req=>{const uid=auth(req),rows=Array.isArray(req.data?.signals)?req.data.signals:[];if(rows.length>MAX_SIGNALS)throw new HttpsError('invalid-argument',`Maximum ${MAX_SIGNALS} signals`);const writes=[];let relationCount=0;for(const raw of rows){let signal;try{signal=cleanSignal(raw,uid);}catch(e){throw new HttpsError('invalid-argument',e.message);}writes.push({ref:db.doc(`users/${uid}/signals/${docId(signal.id)}`),data:{...signal,originalId:signal.id,serverUpdatedAt:admin.firestore.FieldValue.serverTimestamp()}});for(const group of ['contacts','companies','projects','objectives'])for(const entity of signal.entities[group]||[]){if(!entity.id)continue;const entityKey=docId(`${entity.type}|${entity.id}`),relationKey=docId(`${signal.id}|${entity.type}|${entity.id}`);writes.push({ref:db.doc(`users/${uid}/entities/${entityKey}`),data:{...entity,userId:uid,entityKey,updatedAt:admin.firestore.FieldValue.serverTimestamp()}});writes.push({ref:db.doc(`users/${uid}/signalRelations/${relationKey}`),data:{userId:uid,signalId:signal.id,signalDocId:docId(signal.id),entityId:entity.id,entityKey,entityType:entity.type,confidence:entity.confidence,matchType:entity.matchType,evidence:entity.evidence,updatedAt:admin.firestore.FieldValue.serverTimestamp()}});relationCount+=1;}}for(let i=0;i<writes.length;i+=400){const batch=db.batch();for(const write of writes.slice(i,i+400))batch.set(write.ref,write.data,{merge:true});await batch.commit();}await audit(uid,'signals.synced',{count:rows.length,relations:relationCount,storeVersion:'5.1.0'});return{synced:rows.length,relations:relationCount};}),
  createIntelligenceActionRequest:onCall(async req=>{const uid=auth(req),signalId=String(req.data?.signalId||''),action=String(req.data?.action||'');if(!signalId||!ALLOWED_ACTIONS.has(action))throw new HttpsError('invalid-argument','Invalid signal or action');const signalRef=db.doc(`users/${uid}/signals/${docId(signalId)}`),snap=await signalRef.get();if(!snap.exists)throw new HttpsError('not-found','Signal not found');const ref=db.collection(`users/${uid}/actionRequests`).doc();await ref.set({userId:uid,signalId,action,label:String(req.data?.label||action).slice(0,160),status:'pending',proposal:cleanProposal(req.data?.proposal),createdAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp()});await audit(uid,'action.requested',{requestId:ref.id,signalId,action});return{requestId:ref.id,status:'pending'};}),
  approveIntelligenceAction:onCall(async req=>{const uid=auth(req),id=String(req.data?.requestId||''),ref=db.doc(`users/${uid}/actionRequests/${id}`),snap=await ref.get();if(!snap.exists)throw new HttpsError('not-found','Action request not found');if(snap.data().status!=='pending')throw new HttpsError('failed-precondition','Action is not pending');await ref.update({status:'approved',approvedBy:uid,approvedAt:admin.firestore.FieldValue.serverTimestamp(),updatedAt:admin.firestore.FieldValue.serverTimestamp()});await audit(uid,'action.approved',{requestId:id,signalId:snap.data().signalId,action:snap.data().action});return{requestId:id,status:'approved'};}),
  rejectIntelligenceAction:onCall(async req=>{const uid=auth(req),id=String(req.data?.requestId||''),ref=db.doc(`users/${uid}/actionRequests/${id}`),snap=await ref.get();if(!snap.exists)throw new HttpsError('not-found','Action request not found');await ref.update({status:'rejected',rejectionReason:String(req.data?.reason||'').slice(0,500),updatedAt:admin.firestore.FieldValue.serverTimestamp()});await audit(uid,'action.rejected',{requestId:id,signalId:snap.data().signalId,action:snap.data().action});return{requestId:id,status:'rejected'};}),
  executeApprovedIntelligenceAction:onCall(async req=>{const uid=auth(req),id=String(req.data?.requestId||''),ref=db.doc(`users/${uid}/actionRequests/${id}`),snap=await ref.get();if(!snap.exists)throw new HttpsError('not-found','Action request not found');const row=snap.data();if(row.status!=='approved')throw new HttpsError('failed-precondition','Human approval is required');const artifactRef=db.collection(`users/${uid}/actionArtifacts`).doc();const external=EXTERNAL_ACTIONS.has(row.action);const executionMode=external?'draft_only':'internal_artifact';await artifactRef.set({userId:uid,requestId:id,signalId:row.signalId,action:row.action,status:external?'draft':'ready',proposal:row.proposal||{},externalSideEffect:false,createdAt:admin.firestore.FieldValue.serverTimestamp()});await ref.update({status:'completed',executedAt:admin.firestore.FieldValue.serverTimestamp(),executionMode,artifactId:artifactRef.id,updatedAt:admin.firestore.FieldValue.serverTimestamp()});await audit(uid,'action.completed',{requestId:id,signalId:row.signalId,action:row.action,executionMode,artifactId:artifactRef.id});return{requestId:id,status:'completed',action:row.action,signalId:row.signalId,executionMode,artifactId:artifactRef.id,externalSideEffect:false};})
 };
}
module.exports={createHandlers,ALLOWED_ACTIONS,cleanSignal,docId};
