'use strict';
(function initDecisionOS(root) {
  const core = root.SIGMA_DECISION_OS_CORE;
  if (!core) { console.error('[Decision OS] core.js absent'); return; }
  const STORAGE = 'sigma.decision-os.feedback.v1';
  let current = null, stateCache = null, resultCache = null, scheduled = false;
  const esc = value => String(value == null ? '' : value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function loadFeedback(){ try { return JSON.parse(localStorage.getItem(STORAGE) || '{}'); } catch { return {}; } }
  function saveFeedback(id, status){ const data=loadFeedback(); data[id]={status,at:new Date().toISOString()}; localStorage.setItem(STORAGE,JSON.stringify(data)); }
  function engineResult(state){ const engine=root.SIGMA_DECISION_ENGINE; if(!engine?.decideLegacyState) return null; const capacity=Number(state?.settings?.todayCapacityMinutes || Number(state?.settings?.todayEnergy||4)*45 || 180); return engine.decideLegacyState(state,{capacityMinutes:capacity}); }
  function badge(d){ const c=d.os.classification; return `<span class="dos-badge ${c}">${c==='risk'?'Risque':c==='opportunity'?'Opportunité':'Priorité'}</span>`; }
  function card(d,index){ const fb=loadFeedback()[d.id]; return `<article class="dos-card" data-decision-id="${esc(d.id)}"><div class="dos-card-head"><span class="dos-rank">${String(index+1).padStart(2,'0')}</span><div>${badge(d)}<h3>${esc(d.os.title)}</h3></div><strong class="dos-confidence">${d.os.confidence}%</strong></div><p>${esc(d.os.explanation)}</p><div class="dos-metrics"><span>${d.os.effortMinutes} min</span><span>Impact ${Math.round(Number(d.dimensions?.impact||0)*10)}%</span><span>Objectif ${d.os.goalAlignment.score}%</span><span>Confiance source ${d.os.trust.score}%</span></div><div class="dos-actions"><button data-dos-action="act">${esc(d.os.actionLabel)}</button><button data-dos-action="later">Plus tard</button><button data-dos-action="explain">Pourquoi ?</button><button data-dos-action="ignore">Ignorer</button></div>${fb?`<small class="dos-feedback">Retour enregistré : ${esc(fb.status)}</small>`:''}</article>`; }
  function ensureShell(){ let shell=document.getElementById('sigma-decision-os'); if(shell) return shell; const anchor=document.getElementById('dashboard-priority-one')?.closest('.card') || document.getElementById('dashboard-priority-one'); if(!anchor) return null; shell=document.createElement('section'); shell.id='sigma-decision-os'; shell.className='dos-shell card'; shell.innerHTML='<div class="dos-heading"><div><span class="eyebrow">SIGMA DECISION OS</span><h2>Centre de décision</h2><p id="dos-summary"></p></div><button class="button secondary small" data-dos-open="brief">Brief du jour</button></div><div id="dos-cards" class="dos-grid"></div><div class="dos-tabs"><button data-dos-tab="timeline">Chronologie</button><button data-dos-tab="risks">Risques</button><button data-dos-tab="opportunities">Opportunités</button><button data-dos-tab="graph">Graphe</button></div><div id="dos-panel" class="dos-panel" hidden></div>'; anchor.insertAdjacentElement('afterend',shell); return shell; }
  function renderPanel(type){ const panel=document.getElementById('dos-panel'); if(!panel||!current)return; panel.hidden=false; if(type==='timeline'){ const labels={now:'Maintenant',next30:'30 prochaines minutes',afternoon:'Cet après-midi',tomorrow:'Demain',week:'Cette semaine'}; panel.innerHTML=Object.entries(current.timeline).map(([k,items])=>`<section><h4>${labels[k]} <span>${items.length}</span></h4>${items.length?items.map(d=>`<div class="dos-line"><strong>${esc(d.os.title)}</strong><small>${d.os.effortMinutes} min</small></div>`).join(''):'<small>Aucune décision</small>'}</section>`).join(''); }
    else if(type==='risks'||type==='opportunities'){ const rows=current[type]; panel.innerHTML=`<h3>${type==='risks'?'Risques à surveiller':'Opportunités détectées'}</h3>${rows.length?rows.map((d,i)=>card(d,i)).join(''):'<p>Aucun élément détecté.</p>'}`; }
    else if(type==='graph'){ panel.innerHTML=`<h3>Graphe de décision</h3><p>${current.graph.nodes.length} nœuds · ${current.graph.edges.length} relations</p><div class="dos-graph-list">${current.graph.edges.slice(0,20).map(e=>`<code>${esc(e.from)} → ${esc(e.to)} (${esc(e.type)})</code>`).join('')}</div>`; }
  }
  function explain(d){ const drawer=document.createElement('dialog'); drawer.className='dos-dialog'; drawer.innerHTML=`<form method="dialog"><button class="dos-close">×</button><span class="eyebrow">Décision explicable</span><h2>${esc(d.os.title)}</h2><p>${esc(d.os.explanation)}</p><dl><dt>Action</dt><dd>${esc(d.os.actionLabel)}</dd><dt>Score</dt><dd>${Math.round(Number(d.score||0))}</dd><dt>Confiance</dt><dd>${d.os.confidence}%</dd><dt>Effort</dt><dd>${d.os.effortMinutes} min</dd><dt>Alignement objectifs</dt><dd>${d.os.goalAlignment.score}%</dd><dt>Règles</dt><dd>${esc((d.rules||[]).join(', ')||'Aucune règle nommée')}</dd><dt>Incertitude</dt><dd>${d.os.trust.uncertainty}%</dd></dl></form>`; document.body.appendChild(drawer); drawer.addEventListener('close',()=>drawer.remove()); drawer.showModal(); }
  function dailyBrief(){ if(!current)return; const drawer=document.createElement('dialog'); drawer.className='dos-dialog'; drawer.innerHTML=`<form method="dialog"><button class="dos-close">×</button><span class="eyebrow">Daily Brain</span><h2>Votre brief du jour</h2><div class="dos-brief"><strong>${current.decisions.length}</strong><span>décisions</span><strong>${current.risks.length}</strong><span>risques</span><strong>${current.opportunities.length}</strong><span>opportunités</span><strong>${current.plannedMinutes}</strong><span>minutes planifiées</span></div><p>Capacité estimée : ${current.capacityMinutes} minutes. ${current.plannedMinutes>current.capacityMinutes?'Le plan dépasse la capacité : reportez les éléments à faible score.':'Le plan respecte votre capacité actuelle.'}</p></form>`; document.body.appendChild(drawer); drawer.addEventListener('close',()=>drawer.remove()); drawer.showModal(); }
  function render(){ scheduled=false; const shell=ensureShell(); if(!shell)return; const state=root.SigmaApp?.getState?.()||{}; let result; try{result=engineResult(state);}catch(error){console.error('[Decision OS] moteur',error);return;} if(!result)return; stateCache=state; resultCache=result; current=core.build(result,state,{limit:12}); document.getElementById('dos-summary').textContent=`${current.decisions.length} décisions · ${current.risks.length} risque(s) · ${current.opportunities.length} opportunité(s) · ${current.plannedMinutes}/${current.capacityMinutes} min`; document.getElementById('dos-cards').innerHTML=current.decisions.slice(0,3).map(card).join('')||'<p>Aucune décision disponible.</p>'; root.dispatchEvent(new CustomEvent('sigma:decision-os-updated',{detail:{snapshot:current}})); }
  function schedule(){ if(scheduled)return; scheduled=true; requestAnimationFrame(render); }
  document.addEventListener('click',event=>{ const tab=event.target.closest('[data-dos-tab]'); if(tab){renderPanel(tab.dataset.dosTab);return;} if(event.target.closest('[data-dos-open="brief"]')){dailyBrief();return;} const action=event.target.closest('[data-dos-action]'); if(!action)return; const host=action.closest('[data-decision-id]'); const decision=current?.decisions.find(d=>d.id===host?.dataset.decisionId)||current?.risks.find(d=>d.id===host?.dataset.decisionId)||current?.opportunities.find(d=>d.id===host?.dataset.decisionId); if(!decision)return; const type=action.dataset.dosAction; if(type==='explain'){explain(decision);return;} saveFeedback(decision.id,type); if(type==='act'){ const panel=['event','calendar'].includes(decision.sourceType)?'planner':'tasks'; document.querySelector(`[data-panel="${panel}"]`)?.click(); } schedule(); });
  root.addEventListener('sigma:action-center-updated',schedule); root.addEventListener('sigma:command-center-updated',schedule); document.addEventListener('languagechange',schedule); root.SigmaApp?.subscribe?.(schedule); if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule);else schedule();
  root.SIGMA_DECISION_OS=Object.freeze({version:core.VERSION,refresh:schedule,getSnapshot:()=>current,getFeedback:loadFeedback});
})(typeof globalThis!=='undefined'?globalThis:window);
