'use strict';
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.SIGMA_GRAPH_INSPECTOR=api;})(typeof globalThis!=='undefined'?globalThis:window,function(root){
 const vals=n=>Array.isArray(n)?n:Object.values(n||{}),norm=s=>String(s||'').normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').toLowerCase(),label=n=>n?.name||n?.label||n?.title||n?.id||'Unknown';
 const ef=e=>e.from||e.source||e.sourceId,et=e=>e.to||e.target||e.targetId,er=e=>e.type||e.relation||e.label||'related_to';
 function degree(g,id){return(g?.edges||[]).reduce((n,e)=>n+Number(ef(e)===id||et(e)===id),0)}
 function summarize(g){const ns=vals(g?.nodes),byType={};ns.forEach(n=>byType[n.type||'unknown']=(byType[n.type||'unknown']||0)+1);return{version:'8.1.0',nodes:ns.length,edges:(g?.edges||[]).length,signals:Object.keys(g?.signalEntityMap||{}).length,isolatedNodes:ns.filter(n=>degree(g,n.id)===0).length,byType};}
 function search(g,q='',o={}){const t=norm(q),type=norm(o.type||'');return vals(g?.nodes).filter(n=>(!type||norm(n.type)===type)&&(!t||[n.id,label(n),n.type,n.email,...(n.aliases||[])].some(v=>norm(v).includes(t)))).map(n=>({...n,label:label(n),degree:degree(g,n.id)})).sort((a,b)=>b.degree-a.degree||a.label.localeCompare(b.label)).slice(0,o.limit||50);}
 function neighbors(g,id){const map=g?.nodes||{};return(g?.edges||[]).flatMap(e=>ef(e)===id?[{node:map[et(e)]||{id:et(e)},relation:er(e),direction:'out',edge:e}]:et(e)===id?[{node:map[ef(e)]||{id:ef(e)},relation:er(e),direction:'in',edge:e}]:[]);}
 const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
 function mount(target,o={}){if(typeof document==='undefined')throw new Error('Browser required');const host=typeof target==='string'?document.querySelector(target):target;if(!host)throw new Error('Inspector target not found');const mem=o.memory||root.SIGMA_GRAPH_MEMORY;let graph=o.graph||mem?.load?.().graph||root.__SIGMA_LAST_KNOWLEDGE_GRAPH__||{nodes:{},edges:[],signalEntityMap:{}},selected=null,query='';
 host.className+=' sigma-graph-inspector';host.innerHTML=`<section class="sgi"><header><div><b>V8.1 · KNOWLEDGE GRAPH</b><h2>Graph Inspector</h2></div><div><button data-a="refresh">Refresh</button><button data-a="export">Export</button><button data-a="clear">Clear</button></div></header><div class="sgi-stats"></div><input class="sgi-search" placeholder="Search entity or alias"><div class="sgi-grid"><div><h3>Entities</h3><div class="sgi-list"></div></div><div><h3>Relations</h3><div class="sgi-detail">Select an entity.</div></div></div></section>`;
 function render(){const s=summarize(graph),items=search(graph,query);host.querySelector('.sgi-stats').innerHTML=[['Entities',s.nodes],['Relations',s.edges],['Signals',s.signals],['Isolated',s.isolatedNodes]].map(x=>`<article><strong>${x[1]}</strong><span>${x[0]}</span></article>`).join('');host.querySelector('.sgi-list').innerHTML=items.map(n=>`<button data-id="${esc(n.id)}"><span><strong>${esc(n.label)}</strong><small>${esc(n.type||'unknown')}</small></span><b>${n.degree}</b></button>`).join('')||'<p>No entity.</p>';const d=host.querySelector('.sgi-detail');if(!selected){d.innerHTML='<p>Select an entity.</p>';return}const n=graph.nodes?.[selected],rels=neighbors(graph,selected);d.innerHTML=n?`<article class="sgi-card"><small>${esc(n.type||'unknown')}</small><h4>${esc(label(n))}</h4><p>${esc((n.aliases||[]).join(' · '))}</p></article>${rels.map(r=>`<article class="sgi-rel"><span>${r.direction==='out'?'→':'←'}</span><div><strong>${esc(label(r.node))}</strong><small>${esc(r.relation)}</small></div></article>`).join('')||'<p>No relation.</p>'}`:'<p>Entity not found.</p>';}
 host.addEventListener('input',e=>{if(e.target.matches('.sgi-search')){query=e.target.value;render()}});host.addEventListener('click',e=>{const id=e.target.closest('[data-id]')?.dataset.id;if(id){selected=id;render();return}const a=e.target.closest('[data-a]')?.dataset.a;if(a==='refresh'){graph=o.graph||mem?.load?.().graph||root.__SIGMA_LAST_KNOWLEDGE_GRAPH__||graph;render()}if(a==='clear'){mem?.clear?.();graph={nodes:{},edges:[],signalEntityMap:{}};selected=null;render()}if(a==='export'){const blob=new Blob([mem?.exportState?.()||JSON.stringify({graph},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),l=document.createElement('a');l.href=u;l.download='sigma-knowledge-graph.json';l.click();URL.revokeObjectURL(u)}});render();return{refresh:g=>{graph=g||graph;render()},getGraph:()=>graph,destroy:()=>host.replaceChildren()};}
 return{version:'8.1.0',summarize,search,neighbors,mount};
});