'use strict';
(()=>{
 const KEY='sigma_intelligence_v1_primary';
 const COPY={fr:{beta:'Intelligence V1',legacy:'Vue actuelle',title:'Décisions recommandées par SigmaSignal',empty:'Aucun signal réel ne nécessite votre attention.',why:'Pourquoi ?',approval:'Validation humaine requise',confidence:'Confiance',importance:'Importance',urgency:'Urgence',impact:'Impact',open:'Ouvrir la source',relations:'Relations détectées',propose:'Proposer cette action',approve:'Valider',reject:'Refuser',execute:'Confirmer l’exécution',cloud:'Connexion cloud requise',saved:'Signal et historique enregistrés',pending:'Action en attente de validation',done:'Action validée et transmise sans effet externe automatique',primary:'Utiliser V1 par défaut'},en:{beta:'Intelligence V1',legacy:'Current view',title:'Decisions recommended by SigmaSignal',empty:'No real signal currently needs your attention.',why:'Why?',approval:'Human approval required',confidence:'Confidence',importance:'Importance',urgency:'Urgency',impact:'Impact',open:'Open source',relations:'Detected relations',propose:'Propose this action',approve:'Approve',reject:'Reject',execute:'Confirm execution',cloud:'Cloud connection required',saved:'Signal and audit history saved',pending:'Action awaiting approval',done:'Action approved and handed off without automatic external effect',primary:'Use V1 by default'}};
 function initTodayIntelligenceV1(ctx){const host=document.getElementById('v1-today-beta'),toggle=document.getElementById('v1-today-mode-toggle'),legacy=document.getElementById('v17-today-recommendations');if(!host||!toggle||!legacy||!window.SigmaIntelligenceV1?.Engine)return{render(){}};let beta=localStorage.getItem(KEY)==='1',syncTimer=null,current=[];const esc=ctx.escape,copy=()=>COPY[ctx.language()]||COPY.en;
  function badge(label,value){return`<span class="v1-score-badge"><small>${esc(label)}</small><strong>${Math.round(value||0)}</strong></span>`;}
  function relationText(signal){return[...(signal.entities.contacts||[]),...(signal.entities.companies||[]),...(signal.entities.projects||[]),...(signal.entities.objectives||[])].slice(0,4).map(x=>x.label).filter(Boolean).join(' · ');}
  function actionBlock(signal){const sensitive=signal.recommendation.requiresApproval;return`<div class="v1-signal-action"><strong>${esc(signal.recommendation.label)}</strong>${sensitive?`<span class="v1-approval">${esc(copy().approval)}</span>`:''}<button class="button primary small" type="button" data-v1-request="${esc(signal.id)}">${esc(copy().propose)}</button>${signal.source.sourceUrl?`<a class="button secondary small" target="_blank" rel="noopener" href="${esc(signal.source.sourceUrl)}">${esc(copy().open)}</a>`:''}<small data-v1-status="${esc(signal.id)}"></small></div>`;}
  function card(signal,index){const explanation=signal.explanation||{},relation=relationText(signal);return`<article class="v1-signal-card"><div class="v1-signal-rank">${index+1}</div><div class="v1-signal-body"><div class="v1-signal-meta"><span>${esc(signal.source.provider||signal.source.domain)}</span><span>${esc(signal.intelligence.category)}</span><b>${signal.intelligence.priorityScore}/100</b></div><h3>${esc(signal.content.title||signal.content.summary||'Signal')}</h3>${signal.content.sender?`<p class="v1-signal-sender">${esc(signal.content.sender)}</p>`:''}<p>${esc(signal.content.summary||signal.content.body||'')}</p><div class="v1-score-row">${badge(copy().importance,signal.intelligence.importance.score)}${badge(copy().urgency,signal.intelligence.urgency.score)}${badge(copy().impact,signal.intelligence.impact.score)}${badge(copy().confidence,signal.intelligence.confidence.score)}</div><details><summary>${esc(copy().why)}</summary><p>${esc(explanation.summary||'')}</p><ul>${(explanation.factors||[]).map(x=>`<li>${esc(x.label)}</li>`).join('')}</ul>${(explanation.uncertainty||[]).map(x=>`<p class="v1-uncertainty">${esc(x)}</p>`).join('')}${relation?`<p><strong>${esc(copy().relations)} :</strong> ${esc(relation)}</p>`:''}</details></div>${actionBlock(signal)}</article>`;}
  async function sync(){if(!beta||!window.SigmaIntelligenceV1.SignalRepository?.available())return;try{await window.SigmaIntelligenceV1.SignalRepository.sync(current); }catch(e){console.warn('[Sigma Intelligence] sync deferred',e.message);}}
  function scheduleSync(){clearTimeout(syncTimer);syncTimer=setTimeout(sync,1200);}
  function render(){current=window.SigmaIntelligenceV1.Engine.analyzeWorkspace(ctx.getState()).filter(x=>x.status==='new').slice(0,20);const visible=current.slice(0,5);host.innerHTML=`<div class="v1-beta-heading"><div><span class="eyebrow">${esc(copy().beta)}</span><h3>${esc(copy().title)}</h3></div><label class="v1-primary-toggle"><input type="checkbox" data-v1-primary ${beta?'checked':''}> ${esc(copy().primary)}</label></div>${visible.length?visible.map(card).join(''):`<div class="empty-state">${esc(copy().empty)}</div>`}`;host.hidden=!beta;legacy.hidden=beta;toggle.textContent=beta?copy().legacy:copy().beta;toggle.setAttribute('aria-pressed',String(beta));scheduleSync();}
  toggle.addEventListener('click',()=>{beta=!beta;render();});
  host.addEventListener('change',e=>{if(e.target.matches('[data-v1-primary]')){beta=e.target.checked;localStorage.setItem(KEY,beta?'1':'0');render();}});
  host.addEventListener('click',async e=>{const btn=e.target.closest('[data-v1-request]');if(!btn)return;const signal=current.find(x=>x.id===btn.dataset.v1Request),status=host.querySelector(`[data-v1-status="${CSS.escape(btn.dataset.v1Request)}"]`);btn.disabled=true;try{if(!window.SigmaIntelligenceV1.SignalRepository.available())throw new Error(copy().cloud);await window.SigmaIntelligenceV1.SignalRepository.sync([signal]);const req=await window.SigmaIntelligenceV1.ActionService.request(signal);status.textContent=copy().pending;const approved=confirm(`${signal.recommendation.label}\n\n${copy().approval}`);if(!approved){await window.SigmaIntelligenceV1.ActionService.reject(req.requestId,'user_rejected');status.textContent=copy().reject;return;}await window.SigmaIntelligenceV1.ActionService.approve(req.requestId);const execute=confirm(copy().execute);if(execute){await window.SigmaIntelligenceV1.ActionService.execute(req.requestId);status.textContent=copy().done;}else status.textContent=copy().approve;}catch(err){status.textContent=err.message;ctx.toast(err.message);}finally{btn.disabled=false;}});
  ctx.subscribe(render);document.addEventListener('languagechange',render);window.addEventListener('sigma:auth-changed',render);render();return{render};
 }
 window.SUM_MODULES=window.SUM_MODULES||{};window.SUM_MODULES.initTodayIntelligenceV1=initTodayIntelligenceV1;
})();
