'use strict';
(() => {
let financeChart;
function initFinance(ctx) {
  const form=document.getElementById('finance-form');const list=document.getElementById('finance-list');const monthFilter=document.getElementById('finance-month-filter');const typeFilter=document.getElementById('finance-type-filter');
  const currentMonth=()=>ctx.today().slice(0,7);monthFilter.value=currentMonth();
  function filtered(){return ctx.getState().finance.filter(i=>(!monthFilter.value||String(i.date).startsWith(monthFilter.value))&&(typeFilter.value==='all'||i.type===typeFilter.value));}
  function totals(items){const income=items.filter(i=>i.type==='income'&&i.status!=='late').reduce((s,i)=>s+Number(i.amount||0),0);const expense=items.filter(i=>i.type==='expense').reduce((s,i)=>s+Number(i.amount||0),0);return{income,expense,balance:income-expense};}
  function renderChart(items){const canvas=document.getElementById('finance-chart');if(!window.Chart||!canvas)return;const grouped=items.filter(i=>i.type==='expense').reduce((a,i)=>{a[i.category||ctx.t('common.category')]=(a[i.category||ctx.t('common.category')]||0)+Number(i.amount||0);return a},{});financeChart?.destroy();financeChart=new window.Chart(canvas,{type:'doughnut',data:{labels:Object.keys(grouped).length?Object.keys(grouped):['—'],datasets:[{data:Object.keys(grouped).length?Object.values(grouped):[1],backgroundColor:['#5370ff','#18a999','#b75cff','#ff9f43','#3aa3ff','#ef5da8'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'62%',plugins:{legend:{position:'bottom',labels:{usePointStyle:true,boxWidth:8}}}}});}
  function renderTax(items){const professional=items.filter(i=>i.professional!==false);const missing=professional.filter(i=>i.type==='expense'&&!i.receipt).length;const late=items.filter(i=>i.type==='income'&&i.status==='late').length;const expected=items.filter(i=>i.type==='income'&&i.status==='expected').reduce((s,i)=>s+Number(i.amount||0),0);document.getElementById('finance-tax-readiness').innerHTML=`<div class="tax-score"><strong>${Math.max(0,100-missing*12-late*15)}%</strong><span>${ctx.t('finance.readiness')}</span></div><div class="tax-checklist"><p><span>${missing?'!':'✓'}</span>${ctx.t('finance.missingCount',{count:missing})}</p><p><span>${late?'!':'✓'}</span>${ctx.t('finance.lateCount',{count:late})}</p><p><span>→</span>${ctx.t('finance.expectedAmount',{amount:ctx.currency(expected)})}</p></div>`;document.getElementById('finance-missing-total').textContent=String(missing);}
  function render(){const items=filtered();const s=totals(items);document.getElementById('finance-income-total').textContent=ctx.currency(s.income);document.getElementById('finance-expense-total').textContent=ctx.currency(s.expense);document.getElementById('finance-balance-total').textContent=ctx.currency(s.balance);document.getElementById('finance-visible-count').textContent=String(items.length);list.innerHTML=items.length?items.map(i=>`<article class="list-item finance-detail-row"><div class="transaction-icon ${i.type}">${i.type==='income'?'↗':'↘'}</div><div class="list-item-main"><div class="list-item-title">${ctx.escape(i.description)}</div><div class="meta-row"><span>${ctx.escape(i.category)}</span><span>${ctx.formatDate(i.date)}</span><span>${ctx.t(`finance.${i.status||'paid'}`)}</span>${i.professional!==false?`<span>${ctx.t('finance.professional')}</span>`:''}${i.type==='expense'?`<span class="${i.receipt?'receipt-ok':'receipt-missing'}">${i.receipt?ctx.t('finance.receiptReady'):ctx.t('finance.receiptMissing')}</span>`:''}</div></div><strong class="money ${i.type}">${i.type==='income'?'+':'−'}${ctx.currency(i.amount)}</strong><button class="icon-button danger" type="button" data-finance-delete="${i.id}">×</button></article>`).join(''):`<div class="empty-state">${ctx.t('finance.empty')}</div>`;renderChart(items);renderTax(items);}
  form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form),amount=Number(d.get('amount'));if(!amount||amount<=0)return;ctx.updateState(s=>s.finance.unshift({id:ctx.uid(),type:String(d.get('type')),description:String(d.get('description')).trim(),category:String(d.get('category')).trim(),amount,date:String(d.get('date')||ctx.today()),status:String(d.get('status')||'paid'),professional:d.get('professional')==='on',receipt:d.get('receipt')==='on',createdAt:new Date().toISOString()}));form.reset();form.elements.date.value=ctx.today();form.elements.professional.checked=true;ctx.toast(ctx.t('toast.transactionAdded'));});
  list.addEventListener('click',e=>{const b=e.target.closest('[data-finance-delete]');if(b)ctx.updateState(s=>{s.finance=s.finance.filter(i=>i.id!==b.dataset.financeDelete)})});
  monthFilter.addEventListener('change',render);typeFilter.addEventListener('change',render);
  document.getElementById('finance-export-month').addEventListener('click',()=>{const rows=[['date','type','description','category','amount','status','professional','receipt'],...filtered().map(i=>[i.date,i.type,i.description,i.category,i.amount,i.status||'paid',i.professional!==false,i.receipt===true])];const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`sum-finance-${monthFilter.value||currentMonth()}.csv`;a.click();URL.revokeObjectURL(a.href)});
  ctx.subscribe(render);document.addEventListener('languagechange',render);render();return{render};
}
window.SUM_MODULES=window.SUM_MODULES||{};window.SUM_MODULES.initFinance=initFinance;
})();
