'use strict';
const ROLES=Object.freeze({OWNER:'owner',ADMIN:'admin',MEMBER:'member',VIEWER:'viewer'});
const PERMISSIONS=Object.freeze({WORKSPACE_READ:'workspace:read',WORKSPACE_WRITE:'workspace:write',MEMBER_MANAGE:'member:manage',KNOWLEDGE_READ:'knowledge:read',KNOWLEDGE_WRITE:'knowledge:write',AUTOMATION_APPROVE:'automation:approve'});
const ROLE_PERMISSIONS=Object.freeze({owner:Object.values(PERMISSIONS),admin:[PERMISSIONS.WORKSPACE_READ,PERMISSIONS.WORKSPACE_WRITE,PERMISSIONS.MEMBER_MANAGE,PERMISSIONS.KNOWLEDGE_READ,PERMISSIONS.KNOWLEDGE_WRITE,PERMISSIONS.AUTOMATION_APPROVE],member:[PERMISSIONS.WORKSPACE_READ,PERMISSIONS.KNOWLEDGE_READ,PERMISSIONS.KNOWLEDGE_WRITE],viewer:[PERMISSIONS.WORKSPACE_READ,PERMISSIONS.KNOWLEDGE_READ]});
const slug=v=>String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60);
function createWorkspace(input={}){if(!input.ownerId)throw new TypeError('ownerId is required');const now=input.now||new Date().toISOString();const name=String(input.name||'Mon espace Sigma').trim().slice(0,120);return{id:String(input.id||`ws_${Date.now().toString(36)}`),name,slug:slug(input.slug||name)||'sigma',ownerId:String(input.ownerId),status:'active',createdAt:now,updatedAt:now,settings:{locale:input.locale||'fr',timezone:input.timezone||'Europe/Paris',...input.settings}};}
function createMembership({workspaceId,userId,role=ROLES.MEMBER,now=new Date().toISOString()}){if(!workspaceId||!userId)throw new TypeError('workspaceId and userId are required');if(!ROLE_PERMISSIONS[role])throw new TypeError('invalid role');return{workspaceId:String(workspaceId),userId:String(userId),role,status:'active',createdAt:now,updatedAt:now};}
const can=(membership,permission)=>Boolean(membership&&membership.status==='active'&&(ROLE_PERMISSIONS[membership.role]||[]).includes(permission));
module.exports={ROLES,PERMISSIONS,ROLE_PERMISSIONS,slug,createWorkspace,createMembership,can};
