'use strict';
function configured(env) { return Boolean(env.TIKTOK_CLIENT_KEY && env.TIKTOK_CLIENT_SECRET && env.TIKTOK_REDIRECT_URI); }
function authUrl(env, state) { const url = new URL('https://www.tiktok.com/v2/auth/authorize/'); url.searchParams.set('client_key', env.TIKTOK_CLIENT_KEY); url.searchParams.set('scope', env.TIKTOK_SCOPES || 'user.info.basic,video.list'); url.searchParams.set('response_type', 'code'); url.searchParams.set('redirect_uri', env.TIKTOK_REDIRECT_URI); url.searchParams.set('state', state); return url.toString(); }
async function fetchJson(url, options = {}) { const response = await fetch(url, options); const payload = await response.json().catch(() => ({})); const error = payload.error || payload.error_code || payload.data?.error_code; if (!response.ok || (error && error !== 'ok')) throw new Error(payload.error_description || payload.message || payload.data?.description || String(error) || `TikTok request failed (${response.status}).`); return payload; }
async function exchange(env, code) { return fetchJson('https://open.tiktokapis.com/v2/oauth/token/', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ client_key: env.TIKTOK_CLIENT_KEY, client_secret: env.TIKTOK_CLIENT_SECRET, code, grant_type: 'authorization_code', redirect_uri: env.TIKTOK_REDIRECT_URI }) }); }
async function refresh(env, tokens) { if (!tokens.refresh_token) return tokens; const next = await fetchJson('https://open.tiktokapis.com/v2/oauth/token/', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ client_key: env.TIKTOK_CLIENT_KEY, client_secret: env.TIKTOK_CLIENT_SECRET, grant_type: 'refresh_token', refresh_token: tokens.refresh_token }) }); return { ...tokens, ...next, refresh_token: next.refresh_token || tokens.refresh_token }; }
async function account(env, tokens) { const fields = 'open_id,union_id,avatar_url,display_name'; const payload = await fetchJson(`https://open.tiktokapis.com/v2/user/info/?fields=${encodeURIComponent(fields)}`, { headers: { Authorization: `Bearer ${tokens.access_token}` } }); const user = payload.data?.user; if (!user?.open_id) throw new Error('No TikTok account was returned.'); return { provider: 'tiktok', externalId: user.open_id, openId: user.open_id, label: user.display_name || 'TikTok account', capability: 'profile-videos-publishing', tokens }; }
async function listInteractions(env, account, updateTokens) { let tokens = account.auth.tokens; async function request() { return fetchJson('https://open.tiktokapis.com/v2/video/list/?fields=id,title,video_description,duration,cover_image_url,share_url,create_time', { method: 'POST', headers: { Authorization: `Bearer ${tokens.access_token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ max_count: 20 }) }); } let payload; try { payload = await request(); } catch (error) { if (!tokens.refresh_token) throw error; tokens = await refresh(env, tokens); updateTokens(tokens); payload = await request(); } return (payload.data?.videos || []).map((video) => ({ id: `tiktok-video-${video.id}`, accountId: account.id, provider: 'tiktok', type: 'content', title: video.title || 'TikTok publication', content: video.video_description || '', sender: account.label, receivedAt: video.create_time ? new Date(Number(video.create_time) * 1000).toISOString() : new Date().toISOString(), unread: false, requiresReply: false, priority: 35, contentIdea: true, sourceUrl: video.share_url || '' })); }
module.exports = { configured, authUrl, exchange, account, listInteractions };
