'use strict';
require('dotenv').config();
const path = require('node:path'); const crypto = require('node:crypto'); const express = require('express'); const cors = require('cors'); const helmet = require('helmet'); const cookieParser = require('cookie-parser'); const { rateLimit } = require('express-rate-limit');
const { createStore } = require('./lib/store'); const { signState, verifyState } = require('./lib/state'); const google = require('./lib/providers/google'); const microsoft = require('./lib/providers/microsoft');
const env = process.env; const PORT = Number(env.PORT || 8988); const SESSION_SECRET = env.SESSION_SECRET;
if (!SESSION_SECRET || SESSION_SECRET.length < 24) throw new Error('SESSION_SECRET must contain at least 24 characters.');
const origins = String(env.APP_ORIGINS || 'http://localhost:8080').split(',').map((x)=>x.trim()).filter(Boolean); const returnUrl = env.APP_RETURN_URL || `${origins[0]}/app.html#connections`;
const store = createStore(path.join(__dirname,'.data','calendar-store.enc.json'), env.TOKEN_ENCRYPTION_KEY); const app = express(); app.set('trust proxy',1);
app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}})); app.use(cors({origin(origin,cb){if(!origin||origins.includes(origin)) return cb(null,true); cb(new Error('Origin not allowed.'));},credentials:true})); app.use(express.json({limit:'32kb'})); app.use(cookieParser(SESSION_SECRET)); app.use(rateLimit({windowMs:60000,limit:120,standardHeaders:true,legacyHeaders:false}));
app.use((req,res,next)=>{let id=req.signedCookies.sigma_calendar_session;if(!id){id=crypto.randomUUID();const sameSite=env.COOKIE_SAME_SITE||'lax';res.cookie('sigma_calendar_session',id,{signed:true,httpOnly:true,secure:env.NODE_ENV==='production'||sameSite==='none',sameSite,maxAge:180*86400000,path:'/'});}req.sigmaSession=id;next();});
function session(req){return store.getSession(req.sigmaSession);} function adapter(provider){return provider==='google'?google:provider==='microsoft'?microsoft:null;} function clean(a){return{id:a.id,provider:a.provider,email:a.email,label:a.label,status:a.status||'connected',createdAt:a.createdAt};}
function upsert(sid,a){store.updateSession(sid,d=>{d.accounts=(d.accounts||[]).filter(x=>!(x.provider===a.provider&&x.email.toLowerCase()===a.email.toLowerCase()));d.accounts.push(a);});}
function updateTokens(sid,id,tokens){store.updateSession(sid,d=>{const a=(d.accounts||[]).find(x=>x.id===id);if(a)a.auth.tokens=tokens;});}
function redirect(ok,provider,message=''){const u=new URL(returnUrl);u.searchParams.set('calendar',ok?'connected':'error');u.searchParams.set('provider',provider);if(message)u.searchParams.set('message',message.slice(0,180));return u.toString();}
app.get('/health',(_req,res)=>res.json({ok:true,version:'1.7.0',providers:{google:google.configured(env),microsoft:microsoft.configured(env)}}));
app.get('/api/calendar/providers',(_req,res)=>res.json({providers:{google:{configured:google.configured(env),access:'read-only'},microsoft:{configured:microsoft.configured(env),access:'read-only'}}}));
app.get('/api/calendar/accounts',(req,res)=>res.json({accounts:(session(req).accounts||[]).map(clean)}));
app.get('/api/calendar/connect/:provider',(req,res)=>{try{const a=adapter(req.params.provider);if(!a)return res.status(400).json({error:'Unknown calendar provider.'});if(!a.configured(env))return res.status(503).json({error:'Calendar OAuth is not configured.'});const state=signState({sid:req.sigmaSession,provider:req.params.provider},SESSION_SECRET);res.redirect(a.authUrl(env,state,String(req.query.email||'')));}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/calendar/callback/:provider',async(req,res)=>{const provider=req.params.provider;try{const payload=verifyState(req.query.state,SESSION_SECRET);if(payload.sid!==req.sigmaSession||payload.provider!==provider)throw new Error('OAuth session mismatch.');const a=adapter(provider);const result=await a.exchange(env,String(req.query.code||''));upsert(req.sigmaSession,{id:crypto.randomUUID(),provider,email:result.email,label:result.label,status:'connected',createdAt:new Date().toISOString(),auth:{type:'oauth',tokens:result.tokens}});res.redirect(redirect(true,provider));}catch(e){res.redirect(redirect(false,provider,e.message));}});
app.delete('/api/calendar/accounts/:id',(req,res)=>{store.updateSession(req.sigmaSession,d=>{d.accounts=(d.accounts||[]).filter(a=>a.id!==req.params.id);});res.json({ok:true});});
app.get('/api/calendar/events',async(req,res)=>{const rows=[];const errors=[];for(const account of session(req).accounts||[]){try{rows.push(...await adapter(account.provider).listEvents(env,account,t=>updateTokens(req.sigmaSession,account.id,t)));}catch(e){errors.push({accountId:account.id,provider:account.provider,message:e.message});}}rows.sort((a,b)=>String(a.startAt||a.date).localeCompare(String(b.startAt||b.date)));res.json({events:rows,errors});});
app.use((error,_req,res,_next)=>{console.error(error.message);res.status(500).json({error:'Calendar connector error.',detail:env.NODE_ENV==='development'?error.message:undefined});});
app.listen(PORT,()=>console.log(`Sigma Calendar Connector listening on http://localhost:${PORT}`));
